### ISSUE TITLE
Compute Target cannot be used

### ISSUE THREAD

**Issue by wolfganghuse** [Azure/AML-Kubernetes#118]
Hello!
While trying to run the simple-train-cli example i receive to following Error:

Code: UserError
Message: Unknown compute target 'kubeonprem'.

Compute Target is attached successfully within AML Studio... 
This works last week without problems ?

Regards,
Wolfgang

**Comment by Zhong-J** [comment]
Hey Wolf, I will offline ping you on this issue. Need more information, like CLI YAML

**Comment by wolfganghuse** [comment]
Yes, please… after enabling “managed Identity” when adding Compute I was able to run a job.
It also seems that configuration yamls are not processed correctly…

Mit freundlichen Grüßen – With kind regards

Wolfgang Huse

Wolfgang Huse | Solutions Architect DevOps & IOT | Mob.: +49 173 4524010 | ***@***.******@***.***>
Nutanix Germany GmbH | Mies-van-der-Rohe Straße 8 | 80807 München / Germany
Amtsgericht Frankfurt HRB 103234 I Geschäftsführer: Olive Yung-Ho Huang, Aaron M. Boynton

https://nutanixbible.com<https://nutanixbible.com/> - The Nutanix Bible
http://ntnx.info/cesignup – Community Edition webpage
https://youtu.be/XHJKNtwVLN4 – How Nutanix Works (deutsch)
http://go.nutanix.com/size-your-data-center.html – Nutanix Sizer


Von: zhongj ***@***.***>
Datum: Mittwoch, 8. September 2021 um 10:00
An: Azure/AML-Kubernetes ***@***.***>
Cc: Wolfgang Huse ***@***.***>, Author ***@***.***>
Betreff: Re: [Azure/AML-Kubernetes] Compute Target cannot be used (#118)

Hey Wolf, I will offline ping you on this issue. Need more information, like CLI YAML

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Azure_AML-2DKubernetes_issues_118-23issuecomment-2D915009950&d=DwMCaQ&c=s883GpUCOChKOHiocYtGcg&r=EA7FfJqyiMnoplm9WCJEGbT0j2RroN-V706ktmQuHvc&m=gSjPRhlCNwQ7vlwphF6T3_vXuR3DK-EaK3oRkPy2Gzc&s=Ea7c-ZYxSFvkJFsp4YGrbAaWz6-bUoI20Qa-h6caczk&e=>, or unsubscribe [github.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AL5RDG4SIGZCEC27IJY7TTDUA4J2ZANCNFSM5DUCTK5Q&d=DwMCaQ&c=s883GpUCOChKOHiocYtGcg&r=EA7FfJqyiMnoplm9WCJEGbT0j2RroN-V706ktmQuHvc&m=gSjPRhlCNwQ7vlwphF6T3_vXuR3DK-EaK3oRkPy2Gzc&s=KvXjOHdFoUNYGgV9SPcZsxSkz7U66D2Q6fAcM-pOZNk&e=>.
Triage notifications on the go with GitHub Mobile for iOS [apps.apple.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=s883GpUCOChKOHiocYtGcg&r=EA7FfJqyiMnoplm9WCJEGbT0j2RroN-V706ktmQuHvc&m=gSjPRhlCNwQ7vlwphF6T3_vXuR3DK-EaK3oRkPy2Gzc&s=cqBcdZm-9pkX0P2N-X7O0C4ek5nZhW5W7orfbbpS8KU&e=> or Android [play.google.com]<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=s883GpUCOChKOHiocYtGcg&r=EA7FfJqyiMnoplm9WCJEGbT0j2RroN-V706ktmQuHvc&m=gSjPRhlCNwQ7vlwphF6T3_vXuR3DK-EaK3oRkPy2Gzc&s=ShAn4plXOokoAntgRh26sTHDw_MtiFjz5rhT8luAfvs&e=>.

**Comment by Zhong-J** [comment]
Wolf, now I can repeatably reproduce the cases as you described. Only when you do attach operation in Studio, the problem will be triggered. I will ask UI team to  take a look. At the same time, to unblock you, please use CLI or SDK to attach the  compute. I will get back to you for any update.

**Comment by wolfganghuse** [comment]
Ack... using CLI to attach compute was successful and job could be started... it is not shown in Studio GUI but i see pods running. Please still ping me offline...

**Comment by Zhong-J** [comment]
Hey Wolf, I just sent email to you. Hopefully you can receive the email.

**Comment by Bozhong68** [comment]
Hi @wolfganghuse, are you still blocked? if not, can we close the issue?

**Comment by Bozhong68** [comment]
closing the issue
