### ISSUE TITLE
Submitted training job to Kubernetes fails to schedule

### ISSUE THREAD

**Issue by camer314** [Azure/AML-Kubernetes#124]
I am trying out the Kubernetes (AKS) attached compute and am trying to submit a simple training job to the cluster however AML is failing to schedule it with the following error:

_Kubernetes job status : Queued_

_Queue Information : Job is waiting for available resources, that required for 1 instance with 0.60 vCPU(s), 0.98 GB memory and 0 GPU(s). The best-fit compute can only provide 1.90 vCPU(s), 4.46 GB memory and 0 GPU(s). Please continue to wait or change to a smaller instance type if available_

Why is this happening? It seems like the cluster has enough resources for the job.

**Comment by Zhong-J** [comment]
Hi @camer314  for reporting the issue. 
Could you please let me know your job URL with subscription ID, resource group, region and run ID? We will have a check.
You can also find me via email jinzhong@microsoft.com. I'd love to schedule a call with you to discuss more.

**Comment by jacobdanovitch** [comment]
I am also running into this on Azure Arc.

> Queue Information : Job is waiting for available resources, that required for 1 instance with 0.60 vCPU(s), 1.50 GB memory and 0 GPU(s). The best-fit compute can only provide 0.00 vCPU(s), 0.00 GB memory and 0 GPU(s). Please continue to wait or change to a smaller instance type if available at 11/13/2021 19:07:58 +00:00

**Comment by Zhong-J** [comment]
Hi @jacobdanovitch , could you check the compute config in the UI, like
![image](https://user-images.githubusercontent.com/61221578/141782796-903c1ecf-c359-416c-a6a9-81896d7391bc.png)

What's your cluster size (node count, CPU core/memory/GPU per worker)?
Feel free to ping me (Doris Zhong) via Teams.

**Comment by jacobdanovitch** [comment]
@Zhong-J Sorry, the output I pasted was taken from the UI. It matches the output from calling `.serialize()` on the compute instance. UI:

![image](https://user-images.githubusercontent.com/17260949/141805065-1455efd5-6722-48b6-a27c-d8026fb45023.png)

This is a fresh single node cluster with Rancher/k3s on OpenStack; 16 cores, 60Gi RAM, no GPUs. The "continue to wait or change to a smaller instance type" issue might have been transient but my jobs are still failing to schedule and it still seems to be related to the resource limits. The `emptyDir` mounts in the job pods seem to not have storage limits set and it's reserving too much disk space on the host. I may be able to fix this somewhat on my end but it could also be configured in the node selector resources if I could get it to update properly.

Don't think I can ping you on Teams as I'm between internships right now, currently using AML for my graduate research until I'm back next summer.

**Comment by Bozhong68** [comment]
@jacobdanovitch, is this issue resolved? if not please let us know and we will follow up further.

**Comment by tybyers** [comment]
I am also running into this issue on a new AKS cluster

> Queue Information : Job is waiting for available resources, that required for 1 instance with 0.60 vCPU(s), 1.50 GB memory and 0 GPU(s). The best-fit compute can only provide 0.45 vCPU(s), 26.32 GB memory and 0 GPU(s). Please continue to wait or change to a smaller instance type if available. at 10/11/2022 19:32:23 +00:00

Here's the attached compute configuration:
![Screen Shot 2022-10-11 at 3 20 43 PM](https://user-images.githubusercontent.com/6686686/195209037-3e3fe56c-2bd3-43a4-8d12-e54fd9258b2a.png)

This is our AML extension information:
```
NAME              	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                  	APP VERSION
azure-ml-extension	azureml  	1       	2022-10-03 23:08:06.441197722 +0000 UTC	deployed	amlarc-extension-1.1.11	1.16.0    
```

I did get an example hello world program we developed to run successfully 4 days ago, but the last 2 days have been unsuccessful, either seeing a message like the above or just staying in the Queueing state until it times out after ~40 minutes.

I've learned a *lot* of `kubectl` commands the last few days searching for an error, but cannot seem to find a clue. 

fwiw, we have our Azure ML configuration fairly locked down behind a virtual network. Our AKS cluster is shared between many other teams at our company, and I do see that some node usage is much higher the last couple days than it was on Friday, however, there appears to be ample room on other nodes so I'm not sure why the scheduler can't seem to find available space.

**Comment by jiaochenlu** [comment]
@tybyers looks like you used the defaultinstancetype, actually you can [create a custom intance type with specific resource allocation](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-manage-kubernetes-instance-types#create-custom-instance-types) (see this document) , like cpu lower than 0.45, and then specify it to your job.

**Comment by yuyue9284** [comment]
> 

Hi @tybyers , could you send the queued job id so that we can check it in our logs? You could also check the logs of aml-operator,  `kubectl logs -n azureml -l app=aml-operator | grep "snapshot of the current cluster status"`, in the logs it shows the snapshot of current cluster.

**Comment by tybyers** [comment]
@yuyue9284 sure I'll find the most recent failed job -- it queues and then fails after 40 minutes, so there's not one currently.

As for the above command, even without the `grep` this is all I'm getting:
```
(base) tbyers % kubectl logs -n azureml -l app=aml-operator                                                
W1011 19:08:59.198673    3152 azure.go:92] WARNING: the azure auth plugin is deprecated in v1.22+, unavailable in v1.26+; use https://github.com/Azure/kubelogin instead.
To learn more, consult https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
time="2022-10-12T00:34:25Z" level=info msg="listing all the amljobs" component=StaleJobCleaner
time="2022-10-12T00:44:25Z" level=info msg="listing all the amljobs" component=StaleJobCleaner
time="2022-10-12T00:54:25Z" level=info msg="listing all the amljobs" component=StaleJobCleaner
time="2022-10-12T01:04:25Z" level=info msg="listing all the amljobs" component=StaleJobCleaner
time="2022-10-12T01:14:25Z" level=info msg="listing all the amljobs" component=StaleJobCleaner
time="2022-10-12T01:24:25Z" level=info msg="listing all the amljobs" component=StaleJobCleaner
time="2022-10-12T01:34:25Z" level=info msg="listing all the amljobs" component=StaleJobCleaner
time="2022-10-12T01:44:25Z" level=info msg="listing all the amljobs" component=StaleJobCleaner
time="2022-10-12T01:54:25Z" level=info msg="listing all the amljobs" component=StaleJobCleaner
time="2022-10-12T02:04:25Z" level=info msg="listing all the amljobs" component=StaleJobCleaner
```

**Comment by tybyers** [comment]
@yuyue9284 my most recent run, a few hours ago, was "quiet_pear..."

It keeps trying for awhile, then gets evicted at about 41 minutes (consistent with my other tries)

```
(base) tbyers % kubectl logs gateway-<id> -n azureml | grep pear
W1011 19:17:38.875206    3296 azure.go:92] WARNING: the azure auth plugin is deprecated in v1.22+, unavailable in v1.26+; use https://github.com/Azure/kubelogin instead.
To learn more, consult https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
time="2022-10-11 23:30:30" level=info msg="The new job created. RunId: quiet_pear_9gqb38n1rw. Extension Version: 1.1.11" jobId=647ab6f84206fa767e4a574decf15e3b
time="2022-10-11 23:34:41" level=info msg="The new job created. RunId: quiet_pear_9gqb38n1rw. Extension Version: 1.1.11" jobId=647ab6f84206fa767e4a574decf15e3b
time="2022-10-11 23:38:52" level=info msg="The new job created. RunId: quiet_pear_9gqb38n1rw. Extension Version: 1.1.11" jobId=647ab6f84206fa767e4a574decf15e3b
time="2022-10-11 23:43:04" level=info msg="The new job created. RunId: quiet_pear_9gqb38n1rw. Extension Version: 1.1.11" jobId=647ab6f84206fa767e4a574decf15e3b
time="2022-10-11 23:47:15" level=info msg="The new job created. RunId: quiet_pear_9gqb38n1rw. Extension Version: 1.1.11" jobId=647ab6f84206fa767e4a574decf15e3b
time="2022-10-11 23:51:26" level=info msg="The new job created. RunId: quiet_pear_9gqb38n1rw. Extension Version: 1.1.11" jobId=647ab6f84206fa767e4a574decf15e3b
time="2022-10-11 23:55:37" level=info msg="The new job created. RunId: quiet_pear_9gqb38n1rw. Extension Version: 1.1.11" jobId=647ab6f84206fa767e4a574decf15e3b
time="2022-10-11 23:59:48" level=info msg="The new job created. RunId: quiet_pear_9gqb38n1rw. Extension Version: 1.1.11" jobId=647ab6f84206fa767e4a574decf15e3b
time="2022-10-12 00:04:00" level=info msg="The new job created. RunId: quiet_pear_9gqb38n1rw. Extension Version: 1.1.11" jobId=647ab6f84206fa767e4a574decf15e3b
time="2022-10-12 00:08:11" level=info msg="The new job created. RunId: quiet_pear_9gqb38n1rw. Extension Version: 1.1.11" jobId=647ab6f84206fa767e4a574decf15e3b
time="2022-10-12 00:12:22" level=info msg="The new job created. RunId: quiet_pear_9gqb38n1rw. Extension Version: 1.1.11" jobId=647ab6f84206fa767e4a574decf15e3b
```
<img width="1465" alt="Screen Shot 2022-10-11 at 7 19 57 PM" src="https://user-images.githubusercontent.com/6686686/195233940-af4caec3-279f-435b-9257-2d19fa204a64.png">

**Comment by yuyue9284** [comment]
Hi @tybyers 

Did the job pod got created in the cluster? Could you show the output of volcano scheduler after the job arrives at the cluster so that we can have a better understanding.

`kubectl  logs -n azureml -l app=volcano-scheduler`

**Comment by tybyers** [comment]
Hi @yuyue9284 

I just started a new job to get current logs, and think I see a problem in the `volcano-controller` logs " 'system:serviceaccount:azureml:volcano-controllers' not on the list of allowed controller accounts":
```
E1012 15:13:21.264860       1 job_controller_actions.go:387] Failed to create pod azureml-f1fa11ae25d7a3a01eb3af77c3f59244-worker-0 for Job azureml-f1fa11ae25d7a3a01eb3af77c3f59244, err &errors.StatusError{ErrStatus:v1.Status{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:"", RemainingItemCount:(*int64)(nil)}, Status:"Failure", Message:"admission webhook \"sidecar-injector.dapr.io\" denied the request: service account 'system:serviceaccount:azureml:volcano-controllers' not on the list of allowed controller accounts", Reason:"", Details:(*v1.StatusDetails)(nil), Code:400}}
```

The volcano-admission logs don't have anything yet for the new job (5 min after kicking it off). The volcano-scheduler logs don't seem (to me) to be as relevant:

```
(base) tbyers % kubectl logs -n azureml -l app=volcano-scheduler
W1012 08:18:23.061144    5123 azure.go:92] WARNING: the azure auth plugin is deprecated in v1.22+, unavailable in v1.26+; use https://github.com/Azure/kubelogin instead.
To learn more, consult https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins
I1012 15:18:24.070801       1 enqueue.go:62] Added Queue <default> for Job <azureml/azureml-f1fa11ae25d7a3a01eb3af77c3f59244>
I1012 15:18:24.070815       1 enqueue.go:78] Try to enqueue PodGroup to 0 Queues
I1012 15:18:24.070826       1 enqueue.go:103] Leaving Enqueue ...
I1012 15:18:24.070839       1 allocate.go:43] Enter Allocate ...
I1012 15:18:24.070854       1 allocate.go:96] Try to allocate resource to 0 Namespaces
I1012 15:18:24.070873       1 allocate.go:283] Leaving Allocate ...
I1012 15:18:24.070885       1 backfill.go:40] Enter Backfill ...
I1012 15:18:24.070893       1 backfill.go:90] Leaving Backfill ...
I1012 15:18:24.071134       1 session.go:192] Close Session af63e55b-eeef-4382-bdbf-a6e44eed438e
I1012 15:18:24.507918       1 event_handlers.go:284] Deleted pod <azureml/prometheus-prom-prometheus-0> from cache.
```

I did try restarting volcano but I am still getting the same issue.
