### ISSUE TITLE
ArcML Installation and Deletion fails on Mixed-OS AKS-HCI cluster 

### ISSUE THREAD

**Issue by penorouzi** [Azure/AML-Kubernetes#137]
Hey, 

When I try to install/delete the ArcML extension using `az k8s-extension` I received an error that installation/deletion has failed. I dug deeper into the issue and found out that some of the ArcML extension pods are being scheduled wrongly on my Windows nodes thus failing to get pulled and/or run. I believe not all pods installed as part of the extension installation have a node selector specified to only target nodes with Linux OS. This is a big issue since many AKS-HCI customers have Mixed-OS environments in their modernization journey. 

Thanks

**Comment by Bozhong68** [comment]
@penorouzi the issue has been addressed with recent implementation of "nodeSelector" configuration setting for extension creation, please see doc here: https://github.com/Azure/AML-Kubernetes/blob/master/docs/deploy-extension.md#review-azureml-deployment-configuration-settings. Please let me know if you have any feedback about the documentation, i.e. whether it is clear enough for you to try out and test. @Zhong-J 

closing the issue.
