### ISSUE TITLE
How to prevent azureml-fe pod failing to schedule on 2-node clusters

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#154]
Hi,
When deploying to an arc-connected cluster with 2 nodes, azuremlfe fails to schedule the 3rd pod.
Is there any way to configure azureml deployment so that it can be deployed to 2- or even 1- node clusters?
I understand the recommendation is 3 nodes, but there are several scenarios where even 1-node clusters are relevant (edge or remote clusters for simpler workloads).
Thanks

**Comment by Zhong-J** [comment]
Hi @joaocc ,  when you deploy the extension, you can set this config to false explicitly.
<img width="454" alt="image" src="https://user-images.githubusercontent.com/61221578/145767287-5a703651-4a3e-4781-9406-071ac4a10cf1.png">

**Comment by joaocc** [comment]
Great. Thanks!
