### ISSUE TITLE
Any plans to support token-based authentication on non-AKS Azure ARC clusters?

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#156]
Hi,
As per https://docs.microsoft.com/en-us/azure/machine-learning/how-to-authenticate-web-service it seems that token-based authentication will not be available on non-AKS clusters over Azure ARC.
Is supporting this something in the roadmap and, if so, by when?
If not, are there any alternatives to key-based authentication on non-AKS clusters?
Thanks

**Comment by mjaow** [comment]
we've already support token-based auth, set auth_mode: aml_token in online_endpoint yaml to make it work
