### ISSUE TITLE
How to use existing cert-manager/letsencrypt instead of static certificates?

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#157]
When deploying to existing clusters, it would be useful to be able to use existing letsencrypt infrastructure (cert-manager) to generate the certificates required to secure the endpoint. Current deployment option requires static certificates.
Are there any plans to allow this type of integration?
Thanks

**Comment by Zhong-J** [comment]
Thank you @joaocc  for the advice. We don't support it today, and will do more investigation and take this as a feature ask.

**Comment by joaocc** [comment]
Thanks. If direct letsencrypt support is not viable in the short term, being able to specify a secret in kubernetes that contains the certificate (instead of a file in the client machine running the scripts) would already be a big help, as that secret could be synchronized with Azure KeyVault or updated by some management tool (including lets's encrypt clients), achieving a similar outcome to the original request.

**Comment by Zhong-J** [comment]
@mjaow hope to get your comments here.

@joaocc , could you help describe what's the pain to use current solution (static file)? What's the expected behavior? We want to implement something general to cover most of the scenarios. Thank you!

**Comment by mjaow** [comment]
yes, it would be helpful if you could provide some scenarios you'd like to use. If secret need to be synchronized with azure keyvault (or anything in cloud), we need to be ensure that cluster is able to access azure keyvault (from both network flow and auth flow)

**Comment by joaocc** [comment]
Hi. We have standardized on let's encrypt for web traffic due to cost and, more importantly, automation. In the case of k8s means deploying cert-man, and adding ingress annotations to get certificates issued. We also automate DNS mapping (external-dns), and are migrating all secrets to Azure KeyVault to be synchronized via kubernetes-external-secrets.
To get Arc-enabled clusters to use SSL, my understanding is that we only have the option to provide a "traditional" certificate via te --sslCertPemFile / --sslKeyPemFile commands.
From a deployment point of view, this requires us to purchase one or more certificates (depending on whether we can/want to use wildcard ones), and deploying them from CI/CD (in this case, sysadmin workstations) via CLI.

So, for us, the ideal scenario would be to be able to specify something like ingress annotations to allow cert-man (for instance) to get certificates and make them available to azureml-fe. 
Since this doesn't seem to be a short-term possibility, we would love to be able to specify in the CLI that the certificate be obtained from an existing kubernetes secret. This would allow us to separate install from certificate deployment, and even allowing us to make the cert available from a central Azure KeyVault, and synchronize them to the individual clusters via KES/ESO/AKVSP.
A variation of this would be to allow the cert to be obtained directly from Azure KeyVault, even if this meant that it would be a bit more difficult to update than if it was in kubernetes secrets.

Hope this helps. Pls fee free to ping me over email if you need further details. Thanks!

**Comment by Bozhong68** [comment]
Thanks @joaocc. For current AKS model deployment, we have autoSSL support which uses Microsoft certificate, is this something that you are looking for?

**Comment by joaocc** [comment]
We have AKS based workloads where we use that, but it doesn't seem to be available for arc-enabled kubernetes clusters (non-AKS). So, yes, something like that would also do the trick :)

**Comment by Zhong-J** [comment]
Discussed with @mjaow. We think we can support k8s secret as the first step. @mjaow will provide more details here.

**Comment by mjaow** [comment]
Hi @joaocc , we had several questions about it firstly:
1. would your secret follow the pattern like 
```
apiVersion: v1
data:
  cert.pem: {cert-base64-result}
  key.pem: {key-base64-result}
kind: Secret
metadata:
  name: xxxx
  namespace: azureml
type: Opaque
```
which means it is a secret contains data cert.pem and key.pem and stay in namespace azureml. FE in amlarc is staying in azureml namespace and it needs to reference the secret in the same namespace. 
2. do you have some components in cluster to refresh the secret referenced by FE automatically?

**Comment by joaocc** [comment]
Hi. 
#1: Not sure if I understood correctly but will try to clarify. The secret format can be whichever is required by AzureML services.
#2: we can deploy https://external-secrets.io/ or https://github.com/external-secrets/kubernetes-external-secrets to create that secret and then keep it synchronized with AzureKeyVault (in our case) or any other of the supported secret backends. It can be configured place secrets in any namespace.

**Comment by mjaow** [comment]
it would be easier if you're able to manage secret in azureml namespace with the previous format and create extension with parameter like sslSecret (or another name).

**Comment by joaocc** [comment]
Yes. Being able to specify a secret name to be used by the service will enable automating externally managed secrets.

**Comment by Zhong-J** [comment]
@joaocc , our team will triage the feature today.  Could you let me know if this k8s secrete support is your current adoption blocker issue?  What's your next planning to use AMLArc with your customers?

**Comment by joaocc** [comment]
Hi. Thx for the update. Yes, this is one of the issues that will make it harder for us to deploy AzureML on Arc-enabled cluster, as it requires a step that is harder to automate in our context - we use flux2 mainly, which means that the current approach would require us to commit the secret to git. Hope this helps. Thx

**Comment by Zhong-J** [comment]
Hello, we have taken it as high priority work item. Jun will work on it soon. We will support k8s secret as Jun mentioned, so you can provide a secrete name (required to be in azureml namespace) in extension deployment settings. We let you know once we roll out this feature.

**Comment by joaocc** [comment]
That is awesome. Thx
