### ISSUE TITLE
When deploying to Arc-Enabled cluster using Python SDK, Model.deploy() throws exception

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#159]
Existing scripts were working well with AKS clusters as inference targets:
```
self.aks_target = AksCompute(workspace=ws, name=_name)
..
_deployment_cfg = AksWebservice.deploy_configuration(...)
...
Model.deploy(
                    workspace=ws,
                    name=_endpoint_name,
                    models=self.models_to_deploy,
                    inference_config=self.azml_infer_cfg,
                    deployment_config=_deployment_cfg,
                    deployment_target=self.aks_target
            )
```

However, when "_name" refers to an azure-arc enabled k8s cluster, we get an exception:
```
WebserviceException:
	Message: Unsupported ClusterType Kubernetes for the Compute resource Id 'NEWCLUNAME'.
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Unsupported ClusterType Kubernetes for the Compute resource Id 'NEWCLUNAME'."
    }
}
```

We already updated packages to:
```
azureml-core~=1.37.0
azureml-defaults~=1.37.0
azureml-contrib-services~=1.37.0
azureml-contrib-k8s~=0.0.1
```

Questions:
* what is the class needed instead of AksCompute and AksWebservice.deploy_configuration? Are there any samples for this?
* what is the recommended way to detect whether a target is "AKS" or "Kubernetes"?
```Workspace.compute_targets``` raises a notification that it is experimental.

Thanks

**Comment by Bozhong68** [comment]
The class needed is KubernetesCompute: https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.compute.kubernetescompute.kubernetescompute?view=azure-ml-py

@adressel do you have any further comment?

**Comment by adressel** [comment]
An existing compute target can be retrieved like this regardless of its compute type:
```python
from azureml.core.compute import ComputeTarget

ct = ComputeTarget(workspace=ws, name=ct_name)
```

In this case, trying to cast a type `Kubernetes` compute target into a type `AKS` fails.  Like @Bozhong68 said above, you can also use the [Kubernetes](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.compute.kubernetescompute.kubernetescompute?view=azure-ml-py) class directly if you know you're using a `Kubernetes` type compute target.

@Bozhong68 can keep me honest on whether the APIs you mention above (Model.deploy()) are supported for `Kubernetes` type compute targets.  In general, we recommend using the developer platform V2 experience.  An example can be found [here](https://github.com/Azure/AML-Kubernetes/blob/master/docs/simple-flow.md).

**Comment by Bozhong68** [comment]
Thanks @adressel, it is correct that model deployment only supports CLI v2 experience, the traditional Python SDK v1.x API is not supported yet. We are working on Python SDK v2 support.

**Comment by joaocc** [comment]
Thanks for the prompt clarification.
We have some non-trivial automations based on the Python SDK v1.x, and it will take us some time to migrate to a CLI v2 base. Will report on results of using KubernetesCompute instead of AKSCompute. 
Thx

**Comment by joaocc** [comment]
Quick update: replacing AksCompute with KubernetesCompute, while using AksWebservice.deploy_configuration as "deployment_config" param to Model.deploy() doesn't return.
What would be a valid class for "deployment_config" in a call to Model.deploy()?
Thanks

**Comment by Bozhong68** [comment]
@joaocc unfortunately, Model.deploy() API is not supported for Arc-enabled Cluster, neither for KubernetesCompute class.

**Comment by joaocc** [comment]
Ok. Thanks. Will wait for Python SDK v2, and will try the CLI v2 in the meanwhile.

**Comment by joaocc** [comment]
Hi
@adressel / @Bozhong68 could you please point me to a schema defining the format of the deployment and endpoint yaml files in the examples above (or for the YAMLs supported by CLI v2)? 
Thanks

**Comment by joaocc** [comment]
@boz
