### ISSUE TITLE
Facing issue while installing ml extension on managedClusters type AKS

### ISSUE THREAD

**Issue by kusbr** [Azure/AML-Kubernetes#161]
Hi

Getting this error. Provided the version --version 1.0.51 (as per another issue resolution) but didn't help. Please suggest

cli.azure.cli.core.sdk.policies: Request URL: 'https://management.azure.com/subscriptions/<subid>/resourceGroups/dmcml-rg/providers/Microsoft.ContainerService/ManagedClusters/dmcml-aks/providers/Microsoft.KubernetesConfiguration/extensions/aks-ml-extension/operations/f745a358-d9e2-4b2d-9e77-fa5da4f5e5eb?api-Version=2021-09-01'
cli.azure.cli.core.sdk.policies: Request method: 'GET'
cli.azure.cli.core.sdk.policies: Request headers:
cli.azure.cli.core.sdk.policies: 'x-ms-client-request-id': '4310a8fa-61ff-11ec-9121-cdf46ffa9fbe'
cli.azure.cli.core.sdk.policies: 'CommandName': 'k8s-extension create'
cli.azure.cli.core.sdk.policies: 'ParameterSetName': '--name --extension-type --config --cluster-type --resource-group --cluster-name --scope --auto-upgrade-minor-version --configuration-settings --version --debug'
cli.azure.cli.core.sdk.policies: 'User-Agent': 'AZURECLI/2.26.1 (MSI) azsdk-python-mgmt-kubernetesconfiguration/1.0.0b1 Python/3.8.9 (Windows-10-10.0.22000-SP0)'
cli.azure.cli.core.sdk.policies: 'Authorization': '*****'
cli.azure.cli.core.sdk.policies: Request body:
cli.azure.cli.core.sdk.policies: This request has no body
urllib3.connectionpool: https://management.azure.com:443 "GET /subscriptions/<subid>/resourceGroups/dmcml-rg/providers/Microsoft.ContainerService/ManagedClusters/dmcml-aks/providers/Microsoft.KubernetesConfiguration/extensions/aks-ml-extension/operations/f745a358-d9e2-4b2d-9e77-fa5da4f5e5eb?api-Version=2021-09-01 HTTP/1.1" 200 None
cli.azure.cli.core.sdk.policies: Response status: 200
cli.azure.cli.core.sdk.policies: Response headers:
cli.azure.cli.core.sdk.policies: 'Cache-Control': 'no-cache'
cli.azure.cli.core.sdk.policies: 'Pragma': 'no-cache'
cli.azure.cli.core.sdk.policies: 'Transfer-Encoding': 'chunked'
cli.azure.cli.core.sdk.policies: 'Content-Type': 'application/json; charset=utf-8'
cli.azure.cli.core.sdk.policies: 'Content-Encoding': 'gzip'
cli.azure.cli.core.sdk.policies: 'Expires': '-1'
cli.azure.cli.core.sdk.policies: 'Vary': 'Accept-Encoding'
cli.azure.cli.core.sdk.policies: 'x-ms-ratelimit-remaining-subscription-reads': '11988'
cli.azure.cli.core.sdk.policies: 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.sdk.policies: 'api-supported-versions': '2019-11-01-Preview, 2021-05-01-preview, 2021-06-01-preview, 2021-09-01, 2021-11-01-preview, 2022-01-01-preview'
cli.azure.cli.core.sdk.policies: 'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.sdk.policies: 'x-ms-request-id': '14afd4e0-94ec-4ca0-96d2-a7a3cb8173f0'
cli.azure.cli.core.sdk.policies: 'x-ms-correlation-request-id': '14afd4e0-94ec-4ca0-96d2-a7a3cb8173f0'
cli.azure.cli.core.sdk.policies: 'x-ms-routing-request-id': 'SOUTHINDIA:20211221T014845Z:14afd4e0-94ec-4ca0-96d2-a7a3cb8173f0'
cli.azure.cli.core.sdk.policies: 'Date': 'Tue, 21 Dec 2021 01:48:45 GMT'
cli.azure.cli.core.sdk.policies: Response content:
cli.azure.cli.core.sdk.policies: {"id":"/subscriptions/<subid>/resourceGroups/dmcml-rg/providers/Microsoft.ContainerService/ManagedClusters/dmcml-aks/providers/Microsoft.KubernetesConfiguration/extensions/aks-ml-extension/operations/f745a358-d9e2-4b2d-9e77-fa5da4f5e5eb","name":"f745a358-d9e2-4b2d-9e77-fa5da4f5e5eb","status":"Failed","error":{"code":"ExtensionCreationFailed","message":" Error: {failed to install chart from path [] for release [aks-ml-extension]: err [release aks-ml-extension failed, and has been uninstalled due to atomic being set: timed out waiting for the condition]} occurred while doing the operation : {Installing the extension} on the config"}}
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 482, in run
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 521, in _poll
azure.core.polling.base_polling.OperationFailed: Operation failed or canceled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 657, in execute
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 720, in _run_jobs_serially
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 702, in _run_job
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 999, in call
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/init.py", line 987, in call
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 255, in result
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 275, in wait
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/_poller.py", line 192, in _start
File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/core/polling/base_polling.py", line 500, in run
azure.core.exceptions.HttpResponseError: (ExtensionCreationFailed) Error: {failed to install chart from path [] for release [aks-ml-extension]: err [release aks-ml-extension failed, and has been uninstalled due to atomic being set: timed out waiting for the condition]} occurred while doing the operation : {Installing the extension} on the config

cli.azure.cli.core.azclierror: (ExtensionCreationFailed) Error: {failed to install chart from path [] for release [aks-ml-extension]: err [release aks-ml-extension failed, and has been uninstalled due to atomic being set: timed out waiting for the condition]} occurred while doing the operation : {Installing the extension} on the config
az_command_data_logger: (ExtensionCreationFailed) Error: {failed to install chart from path [] for release [aks-ml-extension]: err [release aks-ml-extension failed, and has been uninstalled due to atomic being set: timed out waiting for the condition]} occurred while doing the operation : {Installing the extension} on the config
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x044540B8>]
az_command_data_logger: exit code: 1
cli.main: Command ran in 375.306 seconds (init: 0.399, invoke: 374.907)
telemetry.save: Save telemetry record of length 3547 in cache
telemetry.check: Returns Positive.
telemetry.main: Begin creating telemetry upload process.
telemetry.process: Creating upload process: "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\azure\cli\telemetry_init_.pyc C:\Users\kusbr.azure"
telemetry.process: Return from creating process
telemetry.main: Finish creating telemetry upload process.

**Comment by Zhong-J** [comment]
Hi @kusbr, do you still meet this issue? Could you let me know why you use v1.0.51? Could you also try the latest version?
