### ISSUE TITLE
ClusterRole "blob-external-provisioner-role" in namespace "" exists and cannot be imported into the current release

### ISSUE THREAD

**Issue by krisbock** [Azure/AML-Kubernetes#162]
```
az k8s-extension create --name arcml-extension --extension-type Microsoft.AzureML.Kubernetes \
    --config enableTraining=True  --cluster-type connectedClusters --cluster-name ms-aks --resource-group aks \
    --scope cluster --auto-upgrade-minor-version False

(ExtensionCreationFailed)  
Error: {failed to install chart from path [] for release [arcml-extension]: err [rendered manifests contain a resource that already exists.
 Unable to continue with install: ClusterRole "blob-external-provisioner-role" in namespace "" exists and cannot be imported into the
 current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to 
"Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "arcml-extension"; annotation 
validation error: missing key "meta.helm.sh/release-namespace": must be set to "azureml"]} occurred while doing the operation : 
{Installing the extension} on the config


azure-cli                         2.29.0 *
core                              2.29.0 *
telemetry                          1.0.6

Extensions:
aidls                  0.1.20210406.1279
databricks                         0.7.3
synapse                            0.3.0
connectedk8s                       1.2.1
azure-devops                      0.22.0
k8s-extension                      1.0.3
application-insights              0.1.14
ml                                 2.0.3
```

The deployment process works on a new Arc-enabled AKS cluster, but not on my existing Arc-enabled AKS cluster.

**Comment by krisbock** [comment]
Manually deleted:

- csi-blob* and blob-csi* cluster roles 
- csi-blob* and blob-csi* cluster role bindings
- CSIDrivers for blob/disk/file.csi.azure.com

Receiving different error:
`(ExtensionCreationFailed)  Error: {failed to install chart from path [] for release [arcml-extension]: err [release arcml-extension failed, and has been uninstalled due to atomic being set: timed out waiting for the condition]} occurred while doing the operation : {Installing the extension} on the config`

**Comment by Zhong-J** [comment]
Hi @krisbock , I just wanted to reply to your previous message and see your new message. Actually as you have already have blob driver installed, when you install the extension, you can specify the config-setting blobCsiDriverEnabled to False,
![image](https://user-images.githubusercontent.com/61221578/147723975-9adbaf8a-8e19-433e-931e-a330f2048829.png)

But as you have manually deleted the, let us take a look.

**Comment by krisbock** [comment]
Thanks @Zhong-J, completely missed this option.  My K8s knowledge is limited, so it wasn't clear from the initial error that the issue was related to the blob CSI drivers.. Will try to False option in case I missed something.

**Comment by Zhong-J** [comment]
Hi @krisbock, if you want to delete the existing blob-sci, you would need to delete the relevant service account, cluster role, cluster role binding, damsonSet (csi-blob=node), deployment(csi-blob-controller) and csi driver. After the blob-sci is deleted, you can delete the existing extension referring to https://github.com/Azure/AML-Kubernetes/blob/master/docs/deploy-extension.md#delete-azure-machine-learning-extension, and reinstall it.

**Comment by Zhong-J** [comment]
The extension deletion usually take around 10~15 minutes, you can run kubectl get pod -n azureml to check if there are remaining pods.  The deletion is completed if there is no pods under azureml namespace, and then you can reinstall the extension again.
