### ISSUE TITLE
Schema for deployment and endpoint yaml files (cli v2)

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#163]
Hi,
Where can I find the schema for deployment and endpoint yaml files that are being used as inputs for cli v2?
Thanks

**Comment by Bozhong68** [comment]
@joaocc here is the link https://docs.microsoft.com/en-us/azure/machine-learning/reference-yaml-overview, note some YAML schema doc is in the process of update, notably Kuberenetes OnlineDeployment YAML schema, we will publish the updated doc asap. Please feel free to ping me for any questions.
