### ISSUE TITLE
inference-operator-controller-manager error in EKS cluster in private/public network

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#186]
Hi.
When adding a EKS cluster in VPC, deploying azureml-arc works, but `inference-operator-controller-manager` fails to start with the following error (log):
```
I0325 22:26:29.423643       1 request.go:655] Throttling request took 1.027950514s, request: GET:https://172.20.0.1:443/apis/scheduling.volcano.sh/v1beta1?timeout=32s
2022-03-25T22:26:29.482Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": "127.0.0.1:8080"}
2022-03-25T22:26:29.487Z	ERROR	setup	unable to load ingress address	{"error": "failed to get loadBalancer ip from service azureml/azureml-fe, none loadBalancer ip now"}
main.main
	/workspace/cmd/manager/manager.go:111
runtime.main
	/usr/local/go/src/runtime/proc.go:204
```

This also happens in a cluster installed from start with public+private networking

Deployment of AzureML Arc extension was deployed with:
```
    echo az k8s-extension create \
        --extension-type Microsoft.AzureML.Kubernetes \
        --cluster-type connectedClusters \
        --cluster-name "${THIS_CLU_NAME}" \
        --resource-group "${THIS_CLU_RG}" \
        --name "arcml-extension${THIS_EXT_NAME}" \
        \
        --auto-upgrade True \
        \
        --scope cluster \
        --config \
            enableTraining=true \
            enableInference=true \
            inferenceLoadBalancerHA=False \
            allowInsecureConnections=True \
            installNvidiaDevicePlugin=False 
```

Is there any setting that is required for this EKS scenario?
Thanks

**Comment by Zhong-J** [comment]
@joaocc , does your eks have public load balancer? The configuration by default will require a public loadbalancer for a cluster.

**Comment by joaocc** [comment]
Not sure if I know how to answer that (lack of EKS skills). We had this issue also in an EKS instance with public endpoints, where deploying a standard nginx-ingress-controller chart would create a LB automatically.

**Comment by Zhong-J** [comment]
What's the business driver that you want to use EKS? Will that be used in production?

**Comment by Zhong-J** [comment]
@joaocc , this is a known issue. Our router tried to  get loadbalancer IP, but EKS doesn't use IP, but use hostname instead.  
You can use nodePort instead by setting enablePrivateEndpointNodePort=True

**Comment by joaocc** [comment]
Thx. Could you please clarify if the setting is perhaps "privateEndpointNodeport=True" instead of the one you mentioned above? I'm asking as I could only find this last one in the docs. Thx

**Comment by Bozhong68** [comment]
@joaocc I can confirm your understanding is correct, it is "privateEndpointNodeport=True" config setting

**Comment by joaocc** [comment]
Setting the following options seems to have solved the issue. Closing the case. Thanks!
```
privateEndpointNodePort=True
inferenceRouterServiceType=nodePort
```
