### ISSUE TITLE
Cannot run ML jobs from Azure ML Designer / blobfuse issue

### ISSUE THREAD

**Issue by adrianbojko** [Azure/AML-Kubernetes#195]
Hello,

Launching jobs from the cli (using the provided example) works without any issue, but launching a job from the ML Designer (like the "Automobile Price Prediction" example) does not. I use MicroK8S and Ubuntu 20.04. I followed the steps for Azure ML. 

I need to run the jobs without depending on remote azure storage. That said, even configuring said storage and setting fuse_connection.cfg did not work. 

I get the following errors repeatedly (no matter what I do):

`Unable to attach or mount volumes: unmounted volumes=[8925b547244642262e90b43fc586d633-blobfuse-1], unattached volumes=[8925b547244642262e90b43fc586d633-blobfuse-1 amlarc-runtime amlarc-hosts runtoken job-ssh-keys job-prep-scripts lifecycle-cm kube-api-access-sptvd azureml-compute-8925b547244642262e90b43fc586d633-svc dshm amlarc-scripts varlog 8925b547244642262e90b43fc586d633-blobfuse-0 azureml-compute-8925b547244642262e90b43fc586d633-ssh]: timed out waiting for the condition`

`MountVolume.SetUp failed for volume "8925b547244642262e90b43fc586d633-blobfuse-1" : rpc error: code = Unknown desc = Mount failed with error: exit status 255, output: Unable to start blobfuse due to authentication or connectivity issues. Please check the readme for valid auth setups. no config filedone reading env vars`

I tried installing blobfuse and start the daemonset as specified here: https://github.com/Azure/AML-Kubernetes/blob/e0dc8c0bb3b5a84dede5ddfc0103af60be121175/docs/onprem-baremetal-blobfuse-setup.md, but it did not help.

I tried configuring the kubelet like specified here: https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume/blobfuse but it also did not do anything. Note that for microk8s I changed the file /etc/systemd/system/snap.microk8s.daemon-kubelet.service and changed the line starting with `ExecStart`: `ExecStart=/usr/bin/snap run microk8s.daemon-kubelet`

Finally, it's not possible to install a csi driver as it conflicts with the existing ones (https://github.com/kubernetes-sigs/blob-csi-driver, https://github.com/kubernetes-sigs/blob-csi-driver/tree/master/charts).

Thank you! Azure Arc is fantastic, and I'd really like to make it work.

P.S. : as a side question, what is the best way to make a local folder available to all pods of the azureml namespace?

**Comment by Zhong-J** [comment]
Hi @adrianbojko , thanks for the feedback!
This is a known bug we are tracking that the public dataset can't be mounted successfully. 
To solve the problem, you can add an environment variable in run settings for the run with public dataset as input.  The fix will be released in about 1 month, so you don't need to add the env variable that time. 
![image](https://user-images.githubusercontent.com/61221578/163538315-d18fc3ac-67f0-44cf-a3da-6d326da1b8c6.png)

**Comment by Zhong-J** [comment]
To mount local folder to training pods, you can configure a PV/PVC with special label. the instruction is https://github.com/Azure/AML-Kubernetes/blob/master/docs/pvc.md

**Comment by adrianbojko** [comment]
Thanks for the replies. I did some quick tests using the json variable fix, and the job is now stuck as "scheduled" in the UI although there are no scheduled pods whatsoever in the Arc PC. I'll do further tests.

**Comment by Zhong-J** [comment]
Could you send me a job link with subscription, resource group, region? 

We can set up a dubugging session if needed. Feel free to find me via jinzhong@microsoft.com

**Comment by adrianbojko** [comment]
I sent an email, thanks.

**Comment by Zhong-J** [comment]
@adrianbojko , could you help share your Arc-cluster resource id?

**Comment by yuyue9284** [comment]
> Thanks for the replies. I did some quick tests using the json variable fix, and the job is now stuck as "scheduled" in the UI although there are no scheduled pods whatsoever in the Arc PC. I'll do further tests.
> 
> Note that I cannot send you an email "SenderNotAuthenticatedForGroup; authentication required; Delivery restriction check failed because the sender was not authenticated when sending to this group".

Hello @adrianbojko , found a bug in current implementation, could you leave the namespace to empty/default when attach the compute target and try to submit the job again?

**Comment by adrianbojko** [comment]
> > Thanks for the replies. I did some quick tests using the json variable fix, and the job is now stuck as "scheduled" in the UI although there are no scheduled pods whatsoever in the Arc PC. I'll do further tests.
> > Note that I cannot send you an email "SenderNotAuthenticatedForGroup; authentication required; Delivery restriction check failed because the sender was not authenticated when sending to this group".
> 
> Hello @adrianbojko , found a bug in current implementation, could you leave the namespace to empty/default when attach the compute target and try to submit the job again?

Yes, this fixes the problem! So it's an issue with Kubernetes namespaces. I'll soon send a new email with a recap of bugs/missing features.
