### ISSUE TITLE
Endpoint address

### ISSUE THREAD

**Issue by adrianbojko** [Azure/AML-Kubernetes#196]
When creating an endpoint with the gpu / mnist inference example, it creates an uri like this:
`https://arc-ml/api/v1/endpoint/tf-mnist/score`

- Where does the arc-ml comes from? This makes the deployment fail after provisioning as the uri is unreachable, even from Azure ML workspace. Is it the CName used by the inference certificate? And what would the endpoint uri be for insecure endpoints?

- And is there a way to "bridge" this endpoint through Azure? The Azure Arc PC cannot be accessed from the outside but only through the Azure agents installed on it.

**Comment by Bozhong68** [comment]
@mjaow could you help take a look?

**Comment by Zhong-J** [comment]
- arc-ml is the Cname you specified in extension installation. If you hope to get an insecure endpoint, you can update the extension config to enable "allowInsecureConnection", so the http endpoint can be returned.
- I 'm not sure if I understand your question. If the cluster doesn't have public load balancer, you can enable "nodePort" (with either public or private IP) as inference router when deploying the extension, so the endpoint can be called inside the cluster.

**Comment by adrianbojko** [comment]
- So, after testing, in case of insecure connections the inference uri is whatever external IP assigned to the inference pod. 
- My question is related to how Azure accesses the resources on the Arc-configured PC. From what my tests, it seems that when I configure the arc client or when I _submit_ jobs, the client -> Arc PC connection goes _through Azure servers_ and uses the connection opened by the local Arc PC. Is that right? 
- However, this is not the case for inference. Since the test PC is deep within the company's network, it cannot be reached directly (no routing from outside), which Azure ML tries to do for deployed endpoints. It tries to connect to private IP addresses like 10.0.xxx.xxx and fails. What is the solution in this case? Do I have to deploy a full-blown [VPN between the PC and Azure ML](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-private-link)?

**Comment by Bozhong68** [comment]
@adrianbojko it really depends on your on-premises infrastructure. Could you please share a bit more about your setup, for example what kind of Kubernetes distribution you are using? are you connecting Arc to your work PC? Note if your Kubernetes cluster doesn't support loadBalancer service type, you would need to use nodePort service type when you create extension for inference capabilities. For a more confidential communication, you can reach out my work email bozhlin@microsoft.com.

**Comment by adrianbojko** [comment]
I sent an email, thanks.

**Comment by adrianbojko** [comment]
It seems that a full Azure Private Link setup is needed when installing a Azure Arc server on a network that is not directly exposed to the Internet and Azure Cloud. Otherwise it is not possible to deploy endpoints on a Azure Arc cluster if run on private IP addresses (10.x.x.x) as those cannot be reached by Azure, which then thinks that the deployment failed.

A tutorial is really needed for that.
