### ISSUE TITLE
Set instance type from Azure ML Designer

### ISSUE THREAD

**Issue by adrianbojko** [Azure/AML-Kubernetes#197]
How can I set the instance type when launching a job on an attached Kubernetes cluster from the Azure ML Designer? I can't find this option, jobs always start with the default instance type.

**Comment by Bozhong68** [comment]
@adrianbojko, thanks for feedback. Check this documentation: https://github.com/Azure/AML-Kubernetes/blob/master/docs/instance-type.md. You update "defaultinstancetype" with more CPU/memory resources. AzureML Designer doesn't support custom instance type yet, but you can update "defaultinstancetype" using the instructions there.

**Comment by adrianbojko** [comment]
That's what I thought, I can choose the instance type when using YAML files but could not find the option on AzureML Designer. Do you intend to add this feature?

**Comment by Bozhong68** [comment]
> That's what I thought, I can choose the instance type when using YAML files but could not find the option on AzureML Designer. Do you intend to add this feature?

Yes, it will be on our roadmap

**Comment by adrianbojko** [comment]
Waiting for it, then!
