### ISSUE TITLE
"deploy-extension.md" points to missing "azureml-fe.md"

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#207]
Hi
"https://github.com/Azure/AML-Kubernetes/blob/master/docs/deploy-extension.md" contains a reference to non-existing "https://github.com/Azure/AML-Kubernetes/blob/master/docs/azureml-fe.md"
Thx

**Comment by Zhong-J** [comment]
fixed the link

**Comment by Zhong-J** [comment]
have fixed the broken link
