### ISSUE TITLE
"README.md" points to missing "connect-cluster.md"

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#208]
Main README.md points to non-existing link "https://github.com/Azure/azure-arc-kubernetes-preview/blob/master/docs/custom-registry/connect-cluster.md"
Thx

**Comment by Zhong-J** [comment]
This is link is referring to a private Github repo, since the feature "on-prem container registry" is in private preview owned by Azure Arc team. If you like to participate the private preview, I can connect you with Azure Arc team to grant you the access.

**Comment by joaocc** [comment]
I was just reading the docs and found the broken link. Thanks
