### ISSUE TITLE
extension v1.0.88 installs but 2 pods keep failing

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#209]
Hi,
Installing arcml extension (v1.0.88) from scratch (EKS) seems to work well, but the following pods keep failing:
This is a 3 node cluster (2 CPU and 1 GPU).

Code for arcml-healthcheck.agent==`AgentWarning`. All others mention passed.

## fluent-bit (ns==azureml)
Of a total of 3 pods, 2 of them are correctly scheduled to the CPU nodes, while the one targeting the GPU node is not. (yes, I know that below it says that 2 nodes didn't match...)
```
0/3 nodes are available: 1 Too many pods, 2 node(s) didn't match Pod's node affinity/selector.
```
## k8s-host-device-plugin-daemonset (ns==azureml)
Of a total of 3 pods, 2 of them are correctly scheduled to the CPU nodes, while the one targeting the GPU node is not. (yes, I know that below it says that 2 nodes didn't match...)
```
0/3 nodes are available: 1 Too many pods, 2 node(s) didn't match Pod's node affinity/selector.
```
## arc-monitoring/fluentd (ns==kube-system)
Quite often this specific container will die with the following error
```
terminated
Reason: OOMKilled - exit code: 137
```

## arcml-healthcheck
```
agent:
  code: AgentWarning
  message: '{"aml-operator":0,"amlarc-identity-controller":0,"amlarc-identity-proxy":0,"arcml-extension-kube-state-metrics":0,"azureml-fe":0,"azureml-ingress-nginx-controller":0,"cluster-status-reporter":0,"csi-blob-controller":0,"gateway":0,"inference-operator-controller-manager":0,"metrics-controller-manager":0,"relayserver":0,"volcano-admission":0,"volcano-controllers":0,"volcano-scheduler":0};
    {"csi-blob-node":0,"fluent-bit":1,"k8s-host-device-plugin-daemonset":1}; {"alertmanager-alertmanager":0,"prometheus-prom-prometheus":0};
    {}; Pod/fluent-bit-xfvxc: 0/3 nodes are available: 1 Too many pods, 2 node(s)
    didn''t match Pod''s node affinity/selector.; Pod/k8s-host-device-plugin-daemonset-h89kt:
    0/3 nodes are available: 1 Too many pods, 2 node(s) didn''t match Pod''s node
    affinity/selector.; {"alertmanager-alertmanager-0":0,"aml-operator-f4dbcb94f-qw9vl":0,"amlarc-identity-controller-55f7f6779d-xrt8t":0,"amlarc-identity-proxy-5f487dcb5d-lgd2f":0,"arcml-extension-kube-state-metrics-7dd684b99b-9r86g":0,"azureml-fe-c84555dbd-tpbzm":0,"azureml-ingress-nginx-controller-8654ff5bf7-hh2gm":0,"cluster-status-reporter-79d6cdd98c-6s2nb":0,"csi-blob-controller-7bbcfd86b8-xhvnn":0,"csi-blob-node-b8dvv":0,"csi-blob-node-k26hv":0,"csi-blob-node-k4w79":0,"fluent-bit-kn5jt":0,"fluent-bit-q9wp6":0,"fluent-bit-xfvxc":1,"gateway-857cb858fb-p5mw9":0,"inference-operator-controller-manager-6449465c5-tqr2p":0,"k8s-host-device-plugin-daemonset-46gjh":0,"k8s-host-device-plugin-daemonset-h89kt":1,"k8s-host-device-plugin-daemonset-skxjm":0,"metrics-controller-manager-84f8fbc55f-8xdvc":0,"prometheus-prom-prometheus-0":0,"relayserver-859fc798d8-4h25t":0,"relayserver-859fc798d8-9pl9z":0,"volcano-admission-74f559c556-svc4h":0,"volcano-controllers-56894dd996-d8zx4":0,"volcano-scheduler-774bd78f4-lsx7h":0}; '
  suggestion: https://github.com/Azure/AML-Kubernetes/blob/master/docs/troubleshooting.md
network:
  code: Passed
  message: '[{"url":"pypi.org:443","err":null},{"url":"ppa.launchpad.net:80","err":null},{"url":"myregistry.azurecr.io:443","err":null},{"url":"archive.ubuntu.com:80","err":null},{"url":"security.ubuntu.com:80","err":null},{"url":"northeurope.api.azureml.ms:443","err":null},{"url":"northeurope.experiments.azureml.net:443","err":null},{"url":"myaccount.blob.core.windows.net:443","err":null},{"url":"help.kusto.windows.net:443","err":null},{"url":"myaccount.table.core.windows.net:443","err":null},{"url":"myaccount.queue.core.windows.net:443","err":null}]; '
  suggestion: ""
prometheus:
  code: Passed
  message: 'Found prometheus operator: prometheus-ks-kube-prometh-prometheus; '
  suggestion: ""
```

Ideas welcomed.
Thx

**Comment by Zhong-J** [comment]
@zetiaatgithub , could you help take a look?

**Comment by zetiaatgithub** [comment]
Hi @joaocc ,  As the error message says, there are too many pods running on the GPU node. You can run command below to check pod limitation for your GPU node
`kubectl describe nodes <gpu-node-name> | grep -C 8 pods`
and run this command to check how many pods are running on your GPU node
`kubectl get pod -A -o wide | grep <gpu-node-name> | wc -l`
If this is the problem, you could consider removing useless pods on the GPU node or increasing pod limit to mitigate the problem.
`2 node(s) didn't match Pod's node affinity/selector` means the other two CPU nodes don't meet node affinity requirement. This is in line with expectations. For how Daemonset pods are scheduled, you can refer to this https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#how-daemon-pods-are-scheduled

The error of arc-monitoring/fluentd pod is also caused by insufficient resources. Cleaning up useless pods may help. If it doesn't work, you can file a support ticket for Arc team for help.

**Comment by joaocc** [comment]
I was in the AKS mindset of 110-250 pods per node, and i just noticed the limit in this case was 35! 🤦‍♂️ Should have checked the basics. Sorry for the trouble.
