### ISSUE TITLE
Best practice for taints and tolerations on mixed-use clusters?

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#210]
Hi,
The question considers "mixed use" clusters as those with both CPU and GPU nodepools, where not all are dedicated to ML workloads. Is there any best practices on how to combine taints and tolerations for keeping azureml from interfering with other workloads and vice versa?

For instance, in a cluster with 1 CPU nodepool planned for general workloads (web, data, ...) and system workload (secrets sync, tunnels, ingress controllers, ...) and 2 GPU nodepools, how does one configure arcml extension to deploy some/all pods with a toleration? Inspecting the deployed elements doesn't seem to show any support for that.
Or is it the case that it is preferable to achieve the goal with "nodeselector.somelabel=somevalue" when deploying the k8s-extension?

Thanks

**Comment by Bozhong68** [comment]
Hi @joaocc 

Yes, the AzureML deployment config setting "nodeSelector.someKey=someValue" is exactly for this purpose. With that setting, both AzureML extension components and training/inference workload will be deployed to designated nodes only.

Cheers,
Bozhong

**Comment by Bozhong68** [comment]
@joaocc, by the way, if you have a more intuitive name for this config setting, please suggest. Current config setting name might not be so intuitive for end users to understand.

**Comment by joaocc** [comment]
Hi. Thanks for your prompt response. 
The setting name seems ok, but I believe it is only for "positive matching" (affinity). I haven't seen anything to deal with tolerations that are sometimes configured in dedicated nodes.
For context, this link to a NVIDIA Container Team doc has some interesting points on this topic (https://docs.google.com/document/d/16FPbc7qtqvJNPlk2sBlYOyhIB9DYXvaUQrEPP4bHmxI/edit?usp=sharing) including links to different techniques to achieve these segregation goals without changing many existing pods.
Thx

**Comment by Bozhong68** [comment]
Thanks @joaocc  for great feedback, we will look into this and get back to you.

**Comment by Zhong-J** [comment]
Hi Joao, we discussed with the team. Currently extension deployment only has node selector config. The more advanced scheduling methods like traint/tolerations will be considered after product GA mid of June. 
Could you please elaborate the pain point to use node-selector? And if it's a pain point, do you have workaround for it now?

**Comment by Zhong-J** [comment]
Thanks Joaocc. The scenario makes sense to me.

_We would still need to understand (prob is available) whether should the aml-arc infrastructure pods be deployed (on the generic workload or distributed among the GPU nodes).__

Currently if you want to have training/inference workloads scheduled to GPU node pools, aml-arc infra pods, especially daemonset components have to deploy to GPU node pools. If you specify nodeSelector to target CPU node pools in extension installation config, neither system components nor training/inference workloads will be scheduled to GPU node pools.

But from technical perspective, I think it's doable to have system components only in CPU node pools and training/inference workloads in GPU nodePools. (We are working on decouple the amlarc infra daemonsets and training/inference pods, so training/inference workloads won't depend on those daemonsets soon).
We will touch base after our product GA to make progress on this ask.
