### ISSUE TITLE
Naming endpoints/deployment: cli arg or yaml?

### ISSUE THREAD

**Issue by joaocc** [Azure/AML-Kubernetes#211]
Hi,
Looking at some of the examples (such as `https://github.com/Azure/AML-Kubernetes/blob/master/docs/inference-byoc.md`), when creating endpoints, it seems that the name of the endpoint is given in both cli-arg and in the corresponding file.
Is this a requirement from CLI or can we have the name defined just in YAML?

Example (endpoint)
`endpoint.yml `
```
name: <endpoint name>           # Endpoint_name defined here
compute: azureml:<compute target>
auth_mode: key
```
and
```
az ml online-endpoint create -f endpoint.yml -n ${endpoint_name} --sub ${subscription} -g ${resource_group} -w ${workspace}
                                                   ^^^ and here
```

Example (deployment)
`deployment.yaml`
```
name: <deployment name>   # deployment_name defined here
...
```
and
```
az ml online-deployment create -f deployment.yaml -n blue --endpoint ${endpoint_name} -g --sub ${subscription} -g ${resource_group} -w ${workspace} --all-traffic
                                                     ^^^ and here
```

Another minor point is that probably needs updating is that in v2.3.1 of `ml` extension, online-deployment endpoint flag seems to be `--endpoint-name` and not `--endpoint`
```
az ml online-deployment create --help
...
    --endpoint-name -e             : Name of the online endpoint.
```

**Comment by Zhong-J** [comment]
Hi Joao, the endpoint name can be given either in yaml file, or via CLI argument. Just need to define it for once, so you can just define it in yaml.  I've made some updates to the document. Sorry for the confusion.
