### ISSUE TITLE
microsoft.azureml.kubernetes not registered in region centralindia

### ISSUE THREAD

**Issue by ouphi** [Azure/AML-Kubernetes#274]
Hello,
I am working with a customer located in centralindia with substantial AKS investment.
It seems that microsoft.azureml.kubernetes not registered in region centralindia.
Could you please share a timeline for availability for centralindia.

**Comment by jiaochenlu** [comment]
Hi @ouphi ,
We are unavailable in centralindia at present. 
Thanks for reaching out, we'll look at more new regions supporting and consider the centralindia, I will share the support timeline with you once we aligin internally.
I wonder if you could share more about the customer's information, their plan of project and usage volumn, which would help us to evaluate the prioriy.
