### ISSUE TITLE
Fluent bit error in the new extension installation

### ISSUE THREAD

**Issue by sauryadas** [Azure/AML-Kubernetes#67]
sauryadas@Sauryas-MacBook-Pro  ~/Downloads  k get pods -n azureml
NAME                                                    READY   STATUS             RESTARTS   AGE
aml-mpi-operator-74966db5d8-gpdl8                       1/1     Running            0          6m41s
aml-operator-fbf865974-tjhtf                            1/1     Running            0          6m41s
aml-pytorch-operator-d9b8c4c75-74st2                    1/1     Running            0          6m41s
aml-tf-job-operator-7c5848bd4c-clf4k                    1/1     Running            0          6m41s
azureml-connector-admission-59bdc7489-xmxmt             1/1     Running            0          6m42s
azureml-connector-admission-init-qdmtn                  0/1     Completed          0          6m42s
azureml-connector-controllers-7c6fc78b6b-rwjf9          1/1     Running            0          6m42s
azureml-connector-kube-state-metrics-75ccc8ddf6-c2wr6   1/1     Running            0          6m42s
azureml-connector-scheduler-7845fc897b-pxj94            1/1     Running            0          6m41s
fluent-bit-4x67b                                        0/1     CrashLoopBackOff   4          6m41s
fluent-bit-6z8f4                                        0/1     CrashLoopBackOff   5          6m41s
fluent-bit-spdth                                        0/1     CrashLoopBackOff   5          6m42s
job-exporter-bstv2                                      1/1     Running            0          6m41s
job-exporter-vgjd5                                      1/1     Running            0          6m42s
job-exporter-zwg7z                                      1/1     Running            0          6m41s
metrics-controller-manager-6bf8446d67-6llb6             2/2     Running            0          6m42s
prom-operator-5679ff7c7-cprf7                           2/2     Running            0          6m42s
prometheus-prom-prometheus-0                            3/3     Running            1          6m29s
relay-server-7b4d56cd56-kfsp2                           1/1     Running            0          6m40s
rest-server-c5b987fcf-nsmlh                             1/1     Running            0          6m40s
 sauryadas@Sauryas-MacBook-Pro  ~/Downloads  k logs pod/fluent-bit-4x67b -n azureml
Fluent Bit v1.7.1
* Copyright (C) 2019-2021 The Fluent Bit Authors
* Copyright (C) 2015-2018 Treasure Data
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

Error: Configuration file contains errors. Aborting

[2021/03/29 20:15:07] [  Error] File output-kusto-log-container.conf
[2021/03/29 20:15:07] [  Error] Error in line 8: Key has an empty value
 sauryadas@Sauryas-MacBook-Pro  ~/Downloads  k describe  pod/fluent-bit-4x67b -n azureml
Name:         fluent-bit-4x67b
Namespace:    azureml
Priority:     0
Node:         k8s-agentpool1-37961520-vmss000000/10.240.0.34
Start Time:   Mon, 29 Mar 2021 13:08:17 -0700
Labels:       app=fluent-bit
              controller-revision-hash=5678d68cf9
              kubernetes.io/cluster-service=true
              pod-template-generation=1
              version=v1
Annotations:  kopf.zalando.org/last-handled-configuration:
                {"spec": {"volumes": [{"name": "varlog", "hostPath": {"path": "/var/log", "type": ""}}, {"name": "varlibdockercontainers", "hostPath": {"p...
              kubernetes.io/psp: privileged
              prometheus.io/path: /api/v1/metrics/prometheus
              prometheus.io/port: 2020
              prometheus.io/scrape: true
Status:       Running
IP:           10.240.0.34
IPs:
  IP:           10.240.0.34
Controlled By:  DaemonSet/fluent-bit
Containers:
  fluent-bit:
    Container ID:   docker://a28a68320b9cb7e130ccbca0ff79b3ef52f4d1a51d94ca91401da1d85835d866
    Image:          amlk8s.azurecr.io/public/azureml/amlk8s/docker/preview/fluent-bit-with-kusto:1.0.54
    Image ID:       docker-pullable://amlk8s.azurecr.io/public/azureml/amlk8s/docker/preview/fluent-bit-with-kusto@sha256:e6b3adaaa159f40e3cf0baff49eb85d1d008918b1b37b175bda9f2c5c59db6da
    Port:           2020/TCP
    Host Port:      2020/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 29 Mar 2021 13:15:07 -0700
      Finished:     Mon, 29 Mar 2021 13:15:07 -0700
    Ready:          False
    Restart Count:  5
    Requests:
      cpu:     200m
      memory:  1536Mi
    Liveness:  http-get http://127.0.0.1:2020/healthz delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      HOST:                            0.0.0.0
      PORT:                            2020
      FLUENT_AZURE_BLOB_ADAPTER_PORT:  6200
    Mounts:
      /data/lib/docker/containers from datalibdockercontainers (ro)
      /fluent-bit/etc/ from fluent-bit-config (rw)
      /var/lib/docker/containers from varlibdockercontainers (ro)
      /var/log from varlog (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from fluent-bit-token-zbj8m (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  varlog:
    Type:          HostPath (bare host directory volume)
    Path:          /var/log
    HostPathType:
  varlibdockercontainers:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker/containers
    HostPathType:
  datalibdockercontainers:
    Type:          HostPath (bare host directory volume)
    Path:          /data/lib/docker/containers
    HostPathType:
  fluent-bit-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      fluent-bit-config
    Optional:  false
  fluent-bit-token-zbj8m:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  fluent-bit-token-zbj8m
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     :NoExecute
                 :NoSchedule
                 guarantee/restart:NoExecute
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/network-unavailable:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type     Reason     Age                     From                                         Message
  ----     ------     ----                    ----                                         -------
  Normal   Scheduled  <unknown>               default-scheduler                            Successfully assigned azureml/fluent-bit-4x67b to k8s-agentpool1-37961520-vmss000000
  Normal   Pulling    2m46s (x4 over 7m27s)   kubelet, k8s-agentpool1-37961520-vmss000000  Pulling image "amlk8s.azurecr.io/public/azureml/amlk8s/docker/preview/fluent-bit-with-kusto:1.0.54"
  Normal   Pulled     2m46s (x4 over 6m4s)    kubelet, k8s-agentpool1-37961520-vmss000000  Successfully pulled image "amlk8s.azurecr.io/public/azureml/amlk8s/docker/preview/fluent-bit-with-kusto:1.0.54"
  Normal   Created    2m45s (x4 over 6m)      kubelet, k8s-agentpool1-37961520-vmss000000  Created container fluent-bit
  Normal   Started    2m45s (x4 over 6m)      kubelet, k8s-agentpool1-37961520-vmss000000  Started container fluent-bit
  Warning  BackOff    2m17s (x10 over 3m38s)  kubelet, k8s-agentpool1-37961520-vmss000000  Back-off restarting failed container

**Comment by Bozhong68** [comment]
closing staled issue
