### ISSUE TITLE
KubernetesCompute.attach failes on arc local k8s

### ISSUE THREAD

**Issue by azeltov** [Azure/AML-Kubernetes#71]
from azureml.contrib.core.compute.kubernetescompute import KubernetesCompute

k8s_config = {
}

attach_config = KubernetesCompute.attach_configuration(
resource_id="/subscriptions/5763fde3-4253-480c-928f-dfe1e8888a57/resourceGroups/rg-arc/providers/Microsoft.Kubernetes/connectedClusters/arc-kind",
aml_k8s_config=k8s_config
)

compute_target = KubernetesCompute.attach(ws, "arccompute", attach_config)
compute_target.wait_for_completion(show_output=True)

error:

Creating...............
FailedProvisioning operation finished, operation "Failed"
---------------------------------------------------------------------------
ComputeTargetException                    Traceback (most recent call last)
<ipython-input-7-58ed0306fd44> in <module>
     10 
     11 compute_target = KubernetesCompute.attach(ws, "arccompute", attach_config)
---> 12 compute_target.wait_for_completion(show_output=True)

~/miniconda3/envs/k8s/lib/python3.7/site-packages/azureml/core/compute/compute.py in wait_for_completion(self, show_output, is_delete_operation)
    573                                              'Current state is {}'.format(self.provisioning_state))
    574             else:
--> 575                 raise e
    576 
    577     def _wait_for_completion(self, show_output):

~/miniconda3/envs/k8s/lib/python3.7/site-packages/azureml/core/compute/compute.py in wait_for_completion(self, show_output, is_delete_operation)
    566                                              'state, current provisioning state: {}\n'
    567                                              'Provisioning operation error:\n'
--> 568                                              '{}'.format(self.provisioning_state, error_response))
    569         except ComputeTargetException as e:
    570             if e.message == 'No operation endpoint':

ComputeTargetException: ComputeTargetException:
	Message: Compute object provisioning polling reached non-successful terminal state, current provisioning state: Failed
Provisioning operation error:
{'code': 'InternalServerError', 'message': 'An internal server error occurred. If the problem persists, contact support.'}
	InnerException None
	ErrorResponse 
{
    "error": {
        "message": "Compute object provisioning polling reached non-successful terminal state, current provisioning state: Failed\nProvisioning operation error:\n{'code': 'InternalServerError', 'message': 'An internal server error occurred. If the problem persists, contact support.'}"
    }
}

my status of arc+aml k8s nodes:
(k8s) azeltov@DESKTOP-D59GBAK:~/git/azure-arc-kubernetes-preview$ az k8s-extension create --sub 5763fde3-4253-480c-928f-dfe1e8888a57 -g rg-arc -c arc-kind --cluster-type connectedClusters  --extension-type Microsoft.AzureML.Kubernetes -n azureml-kubernetes-connector --release-train preview --config enableTraining=True^C
(k8s) azeltov@DESKTOP-D59GBAK:~/git/azure-arc-kubernetes-preview$ kubectl get pods -n azureml
NAME                                                        READY   STATUS      RESTARTS   AGE
aml-mpi-operator-847689c694-69z7x                           1/1     Running     0          3m7s
aml-operator-55bb7d4784-jcqnx                               1/1     Running     0          3m7s
aml-pytorch-operator-7fd644b97c-bkffn                       1/1     Running     0          3m7s
aml-tf-job-operator-7c5848bd4c-ckgn9                        1/1     Running     0          3m7s
azureml-kubernetes-connector-admission-78f9b654b6-g67t4     1/1     Running     0          3m7s
azureml-kubernetes-connector-admission-init-tv498           0/1     Completed   0          3m7s
azureml-kubernetes-connector-controllers-547945c795-shtnt   1/1     Running     0          3m7s
azureml-kubernetes-connector-scheduler-746448ff9d-khhzt     1/1     Running     0          3m7s
compute-exporter-d5866df74-zqq7c                            1/1     Running     0          3m7s
job-exporter-lnbzf                                          1/1     Running     0          3m7s
metric-reporter-6756b7dbf8-6lvp6                            1/1     Running     0          3m7s
prometheus-deployment-696b5c8bf8-dt554                      1/1     Running     0          3m7s
relay-server-5f89db5967-54bdp                               1/1     Running     0          3m7s
rest-server-6b76db489c-vl6mz                                1/1     Running     0          3m6s

my extension versions:

(k8s) azeltov@DESKTOP-D59GBAK:~/git/azure-arc-kubernetes-preview$ az extension list -o table
Experimental    ExtensionType    Name           Path                                              Preview    Version
--------------  ---------------  -------------  ------------------------------------------------  ---------  ---------
False           whl              azure-cli-ml   /home/azeltov/.azure/cliextensions/azure-cli-ml   False      1.25.0
False           whl              connectedk8s   /home/azeltov/.azure/cliextensions/connectedk8s   False      0.3.8
False           whl              k8s-extension  /home/azeltov/.azure/cliextensions/k8s-extension  True       0.1PP.15

**Comment by Bozhong68** [comment]
closed, no issue with latest release.
