### ISSUE TITLE
on-prem very low performance with dataset.as_mount() method

### ISSUE THREAD

**Issue by tinuxnet** [Azure/AML-Kubernetes#74]
Using the sample notebook [002-SciKitLearn](https://github.com/Azure/AML-Kubernetes/tree/master/docs/sample-notebooks/002-SciKitLearn)

Experienced very slow performance with .as_mount() method.

A possible workaround:
Using .as_download() methos instead the pipeline on prem bare metal cluster, the required time was drastically reduced from 34mins to 3 mins!

Below the original snippet:
 
```
from azureml.core import ScriptRunConfig
args = ['--data-folder', mnist_file_dataset.as_mount(), '--regularization', 0.5]
src = ScriptRunConfig(source_directory=script_folder,
                      script='train.py', 
                      arguments=args,
                      compute_target=compute_target,
                      environment=env)
```
            
Below the code with as_download() method that solved the performance issue.

```
from azureml.core import ScriptRunConfig
args = ['--data-folder', mnist_file_dataset.as_download(), '--regularization', 0.5]
src = ScriptRunConfig(source_directory=script_folder,
                      script='train.py', 
                      arguments=args,
                      compute_target=compute_target,
                      environment=env)
```

**Comment by youhuatuyh** [comment]
Hi tinuxnet, did you use outbound proxy for the on-prem cluster? Do you still meet the issue on latest release?
