### ISSUE TITLE
on-prem cluster detach does not work

### ISSUE THREAD

**Issue by tinuxnet** [Azure/AML-Kubernetes#75]
Detaching an attached Kubernetes service compute, 
when the portal (ml.azure.com) completed the operation, on the cluster all pods, job and deployments with azureml namespace are not cleaned. 

Trying to re-attach the same cluster from the ml.azure.com portal, the operation fails with the following message:
`Relay resource id or connection string are not provided. Please visit https://aka.ms/amlk8s-troubleshoot-preview for help.`

**Comment by Bozhong68** [comment]
closing the issue as it is not reproducible with latest release.
