### ISSUE TITLE
Attaching Kubernetes service compute, operation success reported "too early"

### ISSUE THREAD

**Issue by tinuxnet** [Azure/AML-Kubernetes#76]
Attaching a Kubernetes service compute from the portal ml.azure.com
the operation prematurely success.
So all the azureml setup on prem cluster is not completed yet.

Possible problems:
- Submitting a job, the experiment fails.
- For some reasons the setup on prem cluster fails despite was a success on the ml.azure.com portal.

**Comment by Bozhong68** [comment]
closing the issue, no repro with latest release.
