### ISSUE TITLE
azureml dependencies needed in environment

### ISSUE THREAD

**Issue by samuel100** [Azure/AML-Kubernetes#90]
A user needs to include azureml dependencies in their environment (see bold below). They should not need to do this - it is different to the side-car method used on AmlCompute.

name: pytorch-env
channels:
    - defaults
    - pytorch
dependencies:
    - python=3.7.0
    - pytorch
    - torchvision
    - pip:
      - mlflow
      **- azureml-mlflow
      - azureml-core
      - azureml-dataprep[pandas,fuse]**

**Comment by Bozhong68** [comment]
closing the issue - the issue is addressed with common runtime integration
